### ISSUE TITLE
LiveProf - Error: The header of an OSC packet didn't contain an OSC address or a #bundle string. Header was:

### ISSUE THREAD

**Issue by Shwing97** [bitfocus/companion-module-audiostrom-liveprofessor#3]
Yesterday I was able to connect without issue, now today I receive these err msgs. I have closed and reopened the apps in every possible variation and still getting the same thing. Tried changing the port and connecting local but still no luck.
<img width="542" alt="Screen Shot 2022-02-11 at 8 36 28 PM" src="https://user-images.githubusercontent.com/59773128/153693446-0d59f25b-20ca-48f5-a2fe-981a9408fe61.png">
<img width="402" alt="Screen Shot 2022-02-11 at 8 36 57 PM" src="https://user-images.githubusercontent.com/59773128/153693452-9e2d0163-2696-4e31-83b1-9893997c824c.png">
 

 instance(LiveProfessor): Error: bind EADDRINUSE 127.0.0.1:8011

 instance(LiveProfessor): Error: The header of an OSC packet didn't contain an OSC address or a #bundle string. Header was:

**Comment by audiostrom** [comment]
This issue was resolved in a LiveProfessor update som time ago. it had to do with the "Ping"-feature
