### ISSUE TITLE
Liveprofessor-Companion Generic Knob for Streamdeck+

### ISSUE THREAD

**Issue by borrisschwarz** [bitfocus/companion-module-audiostrom-liveprofessor#6]
Hi, i'd love to make the rotary knobs on my Streamdeck+ control plugin features in liveprofessor. This would be a gamechanger for live Audio engineering - but its not working (yet).

I figured out that the push funktion on the rotary button is working perfectly as a "generic button" in liveprofessor. But the companion plugin does not seem to support a "generic knob"....so the rotarys are only capable of "on/off" in liveprofessor.

Please, please, please can someone fix that soon?

Let me know if I can give any Support!

**Comment by borrisschwarz** [comment]
Is there any plan to release this feature? Pleeeeeeaase???
If i can support anyhow, let me know!

THIS FEATURE IS A GAMECHANGER FOR LIVEPROFESSOR!

**Comment by audiostrom** [comment]
I know! it's just with the v3 Companion, it requires so much rewrite, So I have not been able to dedicate time to this. If it were just implementing this feature, it would be relatively quick, but rewriting/refactoring the whole module is pretty time-consuming. I'll get around to it, eventually, hope someone else beats me to it though.

**Comment by audiostrom** [comment]
solved in latest commit

**Comment by borrisschwarz** [comment]
Wooohooo! I will check that as soon as possible and give feedback! Thank you sooo much!!
