### ISSUE TITLE
Configuration Timeout

### ISSUE THREAD

**Issue by makesbadnoise** [bitfocus/companion-module-audiostrom-liveprofessor#7]
Liveprofessor connection is timing out before loading info, even when the connection is disabled.
<img width="720" alt="image" src="https://github.com/bitfocus/companion-module-audiostrom-liveprofessor/assets/174636715/bdc84865-bdfb-476c-9c79-9d49b773cadb">

**Comment by makesbadnoise** [comment]
tested on 3.3.1 and 3.4 with no difference in outcome.

**Comment by iron-LAN** [comment]
Is there any progress on this issue? I have the same error with this in de debug log

`Starting up module class: 
Sentry disabled
error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (/Applications/Companion.app/Contents/Resources/bundled-modules/audiostrom-liveprofessor/main.js:2:354816)
    at /Applications/Companion.app/Contents/Resources/bundled-modules/audiostrom-liveprofessor/main.js:2:347875
`

**Comment by iron-LAN** [comment]
I've found out something quite strange. When you install the module it gives you the settings page. All info on there are the default settings. If you use the same settings in Live Professor the module just works.
Until you click save, then the errors happen again and you can only get back to the original settings menu by deleting the module and reinstalling it.

So if you don't click save everything works as expected..

**Comment by audiostrom** [comment]
This should be solved in the last commit. Basically, updating the dependencies seems to fix it.
