### ISSUE TITLE
Generic Button State Feedback doesnt work

### ISSUE THREAD

**Issue by davidrustingha** [bitfocus/companion-module-audiostrom-liveprofessor#8]
Hi,

Not sure how to explain this other than: i've setup some generic buttons for bypassing a plugin. In the previous version of companion this worked perfectly. The color of the button changes depending on the state of the plugin. But I recently upgraded companion and now the colors dont change anymore. Ive tried to create new buttons with the same function; didn't work. Tried it with a blank file and also imported the previous controller file but nothing seems to work.

The Recall View Set feedback and tap-tempo flash do work.

Companion Version: 3.4.2
Live Professor Version: 2024.0.4

**Comment by iron-LAN** [comment]
I've checked other versions of Companion and all versions until V3.4.0 still work.

**Comment by audiostrom** [comment]
This should be resolved in the last commit
